name: Apply Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Project environment selection
        required: true
        options:
          - dev
          - stage
      action:
        type: choice
        description: Action selection [apply/destroy]
        required: true
        default: apply
        options:
          - apply
          - destroy
      apply:
        type: boolean
        description: Execute action
        default: false

jobs:
  apply-composer-terraform:
    name: Deploy GCP Resources with Terraform
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ vars.GCP_REGION }}
      TF_VAR_docker_repository_id: ${{ vars.REPO_NAME }}
      TF_VAR_image_name: ${{ vars.IMAGE_NAME  }}


    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: GCP Authentication
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.IDENTITY }}
          service_account: ${{ secrets.GCP_SA }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Check if GCS Bucket exists
        id: check-bucket
        run: |
          BUCKET_NAME="bank-data-pipeline-tfstate"
          echo "BUCKET_NAME=bank-data-pipeline-tfstate" >> $GITHUB_ENV
          if gsutil ls -b gs://$BUCKET_NAME > /dev/null 2>&1; then
            echo "Bucket exists"
          else
            echo "Bucket does not exists"
            echo "Creating bucket $TFSTATE_BUCKET_NAME..."
            gsutil mb gs://$BUCKET_NAME
          fi


      - name: Build and Push Docker Image
        working-directory: ./bank-data-pipeline
        run: |
            gcloud auth configure-docker europe-north2-docker.pkg.dev
            docker build -t ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.REPO_NAME }}/${{ vars.IMAGE_NAME }}:latest -f Dockerfile .
            docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.REPO_NAME }}/${{ vars.IMAGE_NAME }}:latest
      
      - name: Upload Source Code to GCS Bucket
        working-directory: ./bank-data-pipeline
        run: |
            FOLDER_NAME=$(basename "$PWD")
            CURRENT_DATE=$(date +%Y-%m-%d)
            echo "CURRENT_DATE=${CURRENT_DATE}" 
            ZIPPED_FILE_NAME="${FOLDER_NAME}-${CURRENT_DATE}.zip"
            echo "ZIPPED_FILE_NAME=${ZIPPED_FILE_NAME}"
            zip -r "${ZIPPED_FILE_NAME}" .
            if gsutil ls -b gs://${FOLDER_NAME}-bucket > /dev/null 2>&1; then
              echo "Bucket exists"
            else
              echo "Bucket does not exists"
              echo "Creating bucket ${FOLDER_NAME}-bucket..."
              gsutil mb gs://${FOLDER_NAME}-bucket
            fi
            gsutil cp ./bank-data-pipeline/${ZIPPED_FILE_NAME} gs://${FOLDER_NAME}-bucket/${ZIPPED_FILE_NAME}
            echo "TF_VAR_source_code_name=${ZIPPED_FILE_NAME}" >> $GITHUB_ENV

      - name: Terraform init
        id: init
        working-directory: ./infrastructure/components
        run: |
          terraform init
          terraform workspace select -or-create ${{ github.event.inputs.environment }}

      - name: Terraform Plan
        id: plan
        working-directory: ./infrastructure/components
        run: |
          terraform workspace show
            terraform plan -no-color -input=false -out=tfplan

      - name: Terraform Apply
        id: apply
        if: ${{ inputs.action == 'apply' && inputs.apply == true }}
        working-directory: ./infrastructure/components
        run: |
          terraform workspace show
          terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        id: destroy
        if: ${{ inputs.action == 'destroy' && inputs.apply == true }}
        working-directory: ./infrastructure/components
        run: |
          terraform workspace show
          terraform destroy -auto-approve